- src/main/scala/Difftest.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/difftest/interface.cpp
- src/test/csrc/difftest/interface.h
- src/test/vsrc/common/difftest.v
This commit adds a special field to instruction commit packet. For now,
it is used to indicate that the instruction is a fused instruction. In
the future, we will move isRVC, scFailed, moveElim, etc into this field.
When the instruction is fused, we need to let REF commit one more
instruction.
> difftest: add a special field to instr commit

- src/test/csrc/verilator/emu.cpp
This issue was discussed in https://github.com/OpenXiangShan/difftest/issues/17 and partially resolved in https://github.com/OpenXiangShan/difftest/pull/19
However, in the previous PR, both ready signals for DRAMsim3 & in students' core are delayed for one cycle in the waveform. This PR fix this issue (now ready and valid signals can be high in the same clock cycle).
> emu: fix incorrect waveform in DRAMSim3 cosim

- config/config.h
- src/test/csrc/verilator/emu.cpp
* in case of the situation that the main process meets bug and stops, but the subprocess continues running with no bug.
> lightSSS: stop subprocess when time out

- Makefile
- build.sc
- src/main/scala/DifftestMain.scala
- verilator.mk
1. Make VEXTRA_FLAGS could accept external flags so that developers could give verilator some extra flags such as include directory et al.
2. Add a new target difftest_verilog to generate difftest modules for Verilog design.
> Update support for verilog design

- verilator.mk
v4.204: 880 seconds
v4.218: 1017 seconds
v4.218 with instr-count-dpi: 804 seconds
More info at https://github.com/verilator/verilator/issues/3068.
> verilator: add instr-count-dpi for newer versions

- src/test/csrc/verilator/emu.cpp
This PR originates in a typo where we mistakenly use `-enable-fork` rather than `--enable-fork` (the former one only have one dash).
`-enable-fork` equals to `--log-end nable-fork`, which may eventually disable log dump unexpectedly. We abort execution when encountering non-numeric arguments.
As is written in `print_help` that `--log-end` only accepts numeric argument, it is safe to abort when we type something like that.
Additionally, all other options marked with `=NUM` in `print_help` behaves the same as `--log-end` in this PR.
> emu: add sanity check for numeric arguments

- src/test/vsrc/vcs/top.v
- vcs.mk
Set RANDOMIZE_DELAY to 0 will cause some random initialized reg be
initialized to X. RANDOMIZE_DELAY should satisfy:
* round(RANDOMIZE_DELAY) > 0
* RANDOMIZE_DELAY < reset delay
See https://github.com/chipsalliance/firrtl/pull/835
> vcs: fix incorrect random initialization (X)

- src/test/csrc/verilator/emu.cpp
- src/test/csrc/verilator/emu.h
- verilator.mk
Please use EMU_TRACE=1, EMU_TRACE=vcd or EMU_TRACE=VCD to dump waveform of vcd format, and use EMU_TRACE=fst or EMU_TRACE=FST to dump waveform of fst format.
> Add FST Waveform support

- src/main/scala/Difftest.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/difftest/interface.cpp
- src/test/csrc/difftest/interface.h
1. Add isVsetFirst in DiffInstrCommitIO
2. Skip regs cmp when an incomplete vset is commit in 1 cycle.
> vset support

- .github/workflows/main.yml
- src/main/scala/Difftest.scala
- src/main/scala/DifftestMain.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/difftest/interface.cpp
- src/test/csrc/difftest/interface.h
Add PageCache_refill_check which is similar to icache_refill_check and dcache_refill_check. I have checked that both icache_refill_check and dcache_refill_check can still work after this commit.
> difftest: Add PTW refill check

- src/test/csrc/verilator/emu.cpp
- src/test/csrc/verilator/emu.h
To print reference trace (NEMU only for now), add `--ref-trace` in co-sim args.
For example:
`emu -i ./microbench.bin --ref-trace`
> misc: support always print reference trace

- src/test/csrc/verilator/emu.cpp
* Advance the method call to ensure that the constants read from standard input or file can be correctly passed to dpic
> move `constantinLoad` ahead

- verilator.mk
In some servers, for verilator, if OBJCACHE is not set, ccache will be the default value but ccache is already uninstalled.
So assign empty value to OBJCACHE to aviod ccache.
> mk: assign empty value to OBJCACHE rather than not set

- src/test/csrc/difftest/difftest.cpp
When refill test failed, variable delay will be doubled on every refill check, which can incur overflow and be zeroed
> difftest: fix delay logic of refill test

- src/test/csrc/verilator/emu.cpp
- src/test/csrc/verilator/emu.h
With Verilated::randSeed, we can truly pass seed to Verilator. Otherwise, seeds specified using srand48 will be overwritten by verilator's built-in srand48. 
See more details in Verilator-doc "+verilator+rand+seed" and [https://github.com/verilator/verilator/blob/master/include/verilated.cpp](url)
> emu: explicitly pass seed to verilator with Verilated::randSeed

- .github/workflows/main.yml
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/difftest/difftrace.cpp
- src/test/csrc/difftest/difftrace.h
- src/test/csrc/verilator/emu.cpp
- src/test/csrc/verilator/emu.h
DiffTrace would be the cross-platform data structure for DiffTest. This allows the difftest to be dumped online and restored offline.
> Add support for DiffTrace

- src/main/scala/common/Mem.scala
- src/test/csrc/common/ram.cpp
This commit supports the standardized Chisel interfaces to interact with the simulated memory in difftest.
> common: add universal RAM interfaces

- src/main/scala/DPIC.scala
- src/main/scala/Difftest.scala
We add an extra dummy module to get the implicit clock.
> Remove clock in Difftest IOs

- src/main/scala/Batch.scala
- src/main/scala/Difftest.scala
For now, we only implement a 2D array to store the difftest trace. The sync logic should be further implemented to support the real batch mode.
The sync may reuse other styles such as DPI-C. However, it should be carefully implemented to act like a real batch data transfer. We don't know how it looks like now so we are leaving it empty.
The C++ difftest files also need to support batch mode with an array of DiffTrace as the input. Actually we already have the DiffTrace abstraction, the only thing to do is to avoid calling simulation ticks when dealing with the batch data and resume simulation after it.
> Add preliminary support for batch mode

- src/test/csrc/common/dut.h
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/verilator/emu.h
They are used by both Verilator and VCS.
> dut: move trap values to common/dut

- src/test/csrc/common/ram.h
This is a feature in C++17. However, the legacy C++ compiler used by some VCS installations supports C++11 only.
> ram: avoid using structured binding declarations

- Makefile
- verilator.mk
These flags are moved from verilator.mk to Makefile to allow reuse across various simulation platforms.
> Makefile: add common compiling flags

- src/test/csrc/verilator/emu.cpp
Shared memory resources should be released manually. Otherwise the system would be out of shared memory resources.
> emu: delete lightsss to avoid resource leaks

- src/main/scala/DPIC.scala
- src/test/csrc/difftest/difftest.cpp
Previously we are using the valid bit in the generated C++ function to decide whether to update other fields. However, this brings both performance and functional issues.
When valid is set to false in the hardware, we still need to call the DPI-C function, causing performance overhead. Besides, we still update the valid field in C++. However, the index may be invalid at this time and brings out-of-range memory accesses.
Now we move the valid condition to the enable bit in DPI-C module wrapper. The simulator should avoid calling the DPI-C function when not necessary.
> DPIC: move valid to the wrapper as enable

- .github/workflows/main.yml
- src/main/scala/Difftest.scala
- src/main/scala/Merge.scala
- src/test/csrc/difftest/difftest.h
- src/test/csrc/verilator/emu.cpp
This commit adds preliminary support for merging difftest bundles across various cycles to reduce the memory traffic.
Some cases do not support merging yet and should be identified in the bundle definitions via `supportsMerge` and `supportsBase`. Examples include skipped instructions and store events (to maintain the golden memory).
Currently XiangShan requires ~20K merged difftrace during 100K cycles of simulation with the microbench workload (~100K instructions). NutShell requires ~612 merged difftrace during the 100K cycles of simulation with the microbench workload (~50K instructions). XiangShan requires more merged difftrace because of the existence of StoreEvent to maintain the global golden memory.
> Add preliminary support for merging difftrace

- src/main/scala/Difftest.scala
- src/main/scala/Merge.scala
* fix the merge update of CSRs
For example, cycles after previous instruction commits, the CSRs are changed due to future events. The previous commits should use the previous CSR states for differential testing.
> merge: add support for dependencies

- config/config.h
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/refproxy.cpp
- src/test/csrc/difftest/refproxy.h
- verilator.mk
This change does not impact using Difftest with NEMU.
> Update refproxy to dlopen single riscv64-spike-so file even for multicore.

- src/test/csrc/vcs/vcs_main.cpp
- src/test/vsrc/vcs/top.v
When difftest is not ticked for every clock cycle, the cycles variable may be updated incorrectly. We move the implementation to Verilog to fix it.
> vcs: fix the max-cycles argument in top

- src/main/scala/Squash.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
We add a Blackbox with an exported C/C++ task and a Verilog argument parser to control the enable bit for Squash.
For now, the Verilog argument can only specify a cycle counter to disable the Squash after exceeding specific clock cycles.
> squash: allow enabling/disabling during simulation

- src/main/scala/DPIC.scala
- src/main/scala/Difftest.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
Parent class pointer increment will still use parent class size when pointing to derived class instance
> Fix: replace pointer to instance array with pointer array

- src/main/scala/DPIC.scala
- src/main/scala/Difftest.scala
Before difftest is initialized, io_coreid may be out-of-range. Thus, we have to check whether diffstate_buffer is initialized instead of checking the corresponding pointers are initialized with io_coreid.
This problem causes the failure of previous CIs.
> difftest: fix the init status of diffstate_buffer

- src/main/scala/Bundles.scala
- src/main/scala/Gateway.scala
- src/main/scala/Squash.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
* Before squashed dut_state changes REF, we will first snapshot and record its idx. Temporarily we use naive memcpy for implementation.
* After squashed dut_state trigger error, we will record its idx as replay_idx, then recover REF to state before it works.
* Replay_idx will be passed to HW by DPIC task, then corresponding unsquashed dut_state will be submitted again with same replay_idx.
* We will filter dut_state with different idx, so only first error state will be check again as a series of unsquashed state.
> Difftest: enable squash replay

- src/main/scala/common/Flash.scala
- src/main/scala/common/Mem.scala
- src/test/vsrc/common/SimJTAG.v
When run without difftest, we will use verilog to replace DPIC. Args passing will be optimized later
> Difftest: Add synthesizable implementation for Helpers

- src/test/vsrc/common/SimJTAG.v
Palladium doesn't support set $random to wire. Use dummy logic val to set it.
> SimJTAG: use logic for random

- src/test/vsrc/vcs/AsyncControl.v
- src/test/vsrc/vcs/top.v
Use AsyncControl to support async compare.
Wrap it by TB_ASYNC instead of PALLADIUM, so we can test in other platform.
> TB_ASYNC: Rename GfifoControl to AsyncControl

- palladium.mk
PLDM_CXXFLAGS: add missing + to avoid param overriden
XMSIM_FLAGS: add -PROFTHREAD to support profile for multithread
Ident spaces: modify ident to align
> Fix PLDM_CXXFLAGS and XMSIM_FLAGS in palladium.mk

- palladium.mk
- src/main/scala/common/Flash.scala
- src/main/scala/common/Mem.scala
- src/test/vsrc/common/SimJTAG.v
We remove RANDOMIZE_GARBAGE_ASSIGN and RANDOMIZE_INVALID_ASSIGN because it will cause many DPIC function to get $random, which slow the simulation speed.
Move some display and delay declaration inside module, because some module may sometimes not be used by DUT, declaration in command-line will cause conflict.
> Fix palladium.mk

- Makefile
- palladium.mk
- src/main/scala/DPIC.scala
- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- src/main/scala/Squash.scala
- src/test/vsrc/vcs/DeferredControl.v
- src/test/vsrc/vcs/top.v
- vcs.mk
- verilator.mk
Currently all macros in Gateway can be decided by GatewayConfig, we move macros inside Config for better comprehension.
Difftest-related macros in Verilog can be configured in generated DifftestMacros.v, which should be included by all files use those macros.
Some redundant passing of config and return val of collect is removed. Some macros are renamed for similar format.
> Gen C++ and Verilog macros by GatewayConfig

- .github/workflows/main.yml
- Makefile
- build.sc
- src/main/scala/DPIC.scala
- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- src/main/scala/Squash.scala
Deprecations are not checked because we need to maintain the compatibility with several popular Chisel versions.
> Bump Chisel 6.0.0-RC2 with stricter Scala linting

- src/test/csrc/vcs/vcs_main.cpp
- src/test/vsrc/vcs/DeferredControl.v
Before this commit, we fetch simv_result at 5000 cycles. Only when the result is not zero, it works and stop simulation.
Now we use DPIC task to implement the return of simv_result when not zero, so only one DPIC task will be used to stop simulation. That will reduce the cost of fetch and get result return faster.
> Use DPIC-function to return deferred result

- palladium.mk
- src/main/scala/common/Flash.scala
- src/main/scala/common/Mem.scala
- src/test/vsrc/common/SimJTAG.v
We add macros to turn off DPIC on MemRWHelper and SimJTAG without SYNTHESIS. That means we can reduce number of synchronizations if needed. The new macros is defined in palladium.mk by default.
To add build-in decleration of system task for Palladium, we need to add $.
We declare fwrite in tb_top as Gfifo to reduce synchronizations and speed up simulation.
> Add macros to disable Mem and SimJTAG DPI-C functions

- .github/workflows/main.yml
- build.sc
The official support for RC* and M* versions is removed.
> Bump Chisel 6.0.0

- src/main/scala/common/LogPerfControl.scala
Since https://github.com/chipsalliance/chisel/pull/3753, the users are able to check whether a Data is visible in the current context. To avoid a large number of duplicated LogPerfControl modules, we allow it to be reused when some previous instance is still visible to the current context.
Call `LogPerfControl.reuse(DataMirror.isVisible)` instead of pure `apply()` to allow the reuse.
However, this is still a temporary workaround. In the future, we need some clean methods to extract the simulation environment and access these signals during simulation, possibly via XMR.
> Allow LogPerfControl to be reused if necessary

- palladium.mk
We will generate same verilog code for both SYNTHESIS/no-SYNTHESIS version. 
It should be more simple and clear.
Command may be as follows:
In XiangShan/Nutshell/Other Design：
Build:
make sim-verilog PLDM=1 WITH_CHISELDB=0 WITH_CONSTANTIN=0 MFC=1
make pldm-build SYNTHESIS=1 (no-diff)   ||   make pldm-build (with-diff)
To add extra Macros, we can pass PLDM_EXTRA_MACRO="+define+xxx +define+yyy"
Run:
make pldm-run/pldm-debug SYNTHESIS=1 (no-diff)   ||   make pldm-run/pldm-debug (with-diff)
To add extra running args, we can pass PLDM_EXTRA_ARGS="+workload=../../ready-to-run/microbench.bin +diff=../../ready-to-run/riscv64-nemu-interpreter-so". Note that relative paths should be based on build/pldm-compile
> palladium.mk: rename RELEASE_WITH_ASSERT to SYNTHESIS

- src/main/scala/common/WiringControl.scala
Should return the same data type as the input using polymorphic methods.
> Fix the data type T parameter of WiringControl

- src/main/scala/Bundles.scala
This allows using flatMap to get all valid bits of Seq[BaseBundle].
> Add getValidOption method for DifftestBaseBundle

- src/main/scala/Bundles.scala
* Add apply, toSeq, and names methods to ArchInt/ArchFp/CSR State
* Add === and =/= to ArchInt/ArchFp/CSR State
* Add the default numPhyRegs value to InstrCommit
> Bundles: allow comparison and indexing for ArchRegs

- scripts/coverage/statistics.py
- src/main/scala/common/LogPerfControl.scala
It now allows `module module_name (` as well.
We are not providing general-purpose Verilog parsing scripts. However, we need to at least support Chisel-generated sources using DiffTest. The LogPerfHelp module in DiffTest has a whitespace after module name.
> coverage: fix the regex for module definition

- src/main/scala/Batch.scala
- src/main/scala/DPIC.scala
- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- src/main/scala/Squash.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/vcs/vcs_main.cpp
* We seperate gateway mixed logic to PreProcess, Squash, Batch, GatewaySink and ZoneControl
* We add zone-related logic. DUT will write to different zones of State_Buffer at different clock. And REF will also read different zone at each nstep. It will help with async Read and Write. Also used when step at next cycle may be lag behind transfer.
* Each zone's len will be batchSize when isBatch, default is 1.
* Transfer Module such as DPIC should declare GatewayBundle for same IO interface. And batch will has specific Interface, declare GatewayBatchBundle.
> Gateway: seperate functional component

- src/main/scala/DPIC.scala
- src/main/scala/Gateway.scala
This allows the sink classes to decide their own results, and thus the Gateway class can be simplified without worring about the details of sinks.
> Gateway: return GatewayResult in sink.collect

- src/main/scala/DPIC.scala
For Param configuration in fixed code such as vcs/top.v, we include DifftestMacros.v to contain macros corresponding to Param. However, in generated RTL, we can add Macro directly in code generation. And when pure verilog is generated, DifftestMacros may not be created, which cuase syntax error.
> DPIC: remove include DifftestMacros.v from generated RTL

- src/main/scala/DPIC.scala
DPI-C functions are using the diffstate_buffer to check whether the corresponding data structures have been initialized. However, we are not resetting it to nullptr after free. If the simulation environment is reset manually and restarted, then this pointer will be a dangling pointer and corrupt the next DPI-C calls.
> DPIC: reset diffstate_buffer to nullptr after free

- vcs.mk
In vcs, -y only used for missing modules, +incdir is used for file include. And +incdir is also support by verilator
> vcs: fix including generated vsrc

- src/main/scala/Gateway.scala
- src/test/vsrc/vcs/top.v
For simv, we delay step to ensure DPIC_step behind DPIC_transfer. For emu, when signal enable is high on current cycle, it will be read by Software, however DPIC will be called next cycle because verilog will use previous cycle signals as always block condition.
Such problem is not exposed when step size is fixed, so emu used to step before DPIC. Now we move delay logic to Gateway, so it can be shared by both emu and simv.
> Difftest: delay step for both emu and simv

- vcs.mk
Now we may generate RTL to .sv, we should also search for .sv files for VCS.
By the way, previously use vcs=verilator will not trigger error because verilator will search files automatically.
> vcs: enable search for missing sv files

- .github/workflows/main.yml
- src/main/scala/Batch.scala
- src/main/scala/DPIC.scala
- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- vcs.mk
- verilator.mk
We pack DPIC of DifftestBundles on Hardware and unpack it in Software. So tens of DPIC called times will be reduced to one, which reduce sync times in platform such as palladium.
It can speed up full-difftest of XiangShan from 0.23MHz to 0.29MHz with GlobalEnable,Squash and Gfifo(Non-block) in Palladium. Without Gfifo, it can speed up from 0.025 MHz to 0.11MHz.
Difftest cycle delayed for DifftestBundles to collect valid bundles in bundleNum cycles, which cause delayed comparision result.
BatchInterval and BatchFinish are appended to infoVec to seperate DPIC packed for different Cycle. Other elements contains BundleType and BundleLen to help unpack DataVec.
Now we set maximum data byte packed as 3900, and maximum info byte packed as 90, because Palladium limits total bytes of gfifo param …
> Batch: pack DPIC to reduce sync times

- palladium.mk
- scripts/palladium/argConfigs.qel
- scripts/palladium/clock_gen.xel
- scripts/palladium/compilerOptions.qel
- scripts/palladium/run.tcl
- scripts/palladium/run_debug.tcl
Now we release related palladium scripts and user should set PLDM_HOST for internal information.
We use wildcard for boards occupation in compilerOptions.qel, it can automatically choose approprate boards count. User can also set it manully like {boards 0+1.1+1.2}, which means occupy 1 board and 2 extra domains. It can be estimated by gate count in xe.msg.
> palladium: add scripts

- .github/workflows/main.yml
- src/main/scala/DPIC.scala
- src/main/scala/Gateway.scala
CI used to have a spelling mistake of diffStateSelect, which cause sed incorrectly. Now we rename it to hasDutZone directly, means we have different zones of DUT_buffer, each zone may have 1 or batchSize space.
We clearify inherit and override of DPIC. DPIC/DPICBatch should override modPorts corresponding to input format. CommonPorts(clock, enable) will be filtered from DPICargs, other ports will be used in DPICAssigns
> Fix DPIC arg declaration

- src/test/csrc/vcs/vcs_main.cpp
- src/test/vsrc/vcs/top.v
Add a per-instruction counter to exit, primarily for checkpoint testing
> vcs: add support for --max-instrs option

- .github/workflows/main.yml
- config/config.h
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/difftest/goldenmem.cpp
- src/test/csrc/difftest/goldenmem.h
- src/test/csrc/difftest/refproxy.cpp
- src/test/csrc/difftest/refproxy.h
Previous we use naive memcpy for NEMU memory snapshot. Now we complete more efficient memory snapshot and recovery with NEMU store log.
Call ref_store_log_reset and set_store_log, then we can record origin data of every pmem_write for this execution. When REF and DUT comparation trigger error, call ref_store_log_restore, then memory will recover in reverse order.
ENABLE_STORE_LOG macro added to config.
> Squash replay: optimized by NEMU store log

- .github/workflows/main.yml
- src/main/scala/Batch.scala
- src/main/scala/DPIC.scala
- src/main/scala/Gateway.scala
- src/test/csrc/vcs/vcs_main.cpp
- src/test/vsrc/vcs/DeferredControl.v
- src/test/vsrc/vcs/top.v
* Configurable batchByteLen:  
For better performace without GFIFO. In palladium, we can pass maximum 4000 byte in Gfifo Func (enable isNonBlock), and 8000 byte in Other Func.
With configurable byteLen, speed will increase from 70 K to 98 K without GFIFO.
* Interval step: pack Data transmit and Step control   
Previous when batch is not supported, we use multiple DPIC func to transmit DiffState. Since the DPIC order in one beat is uncertain, we use the step to mark the transmission is finished.
With batch mode, data will be transmit at single func, so we can also pack step to reduce sync times. It can reduce DPIC calls to half. Speed will increase from 95 K to 98 K without GFIFO, 26 K to 27.5 K with GFIFO.
When IntervalStep is enable, step in TOP IO will be default 0. We hold this unused …
> InternalStep: pack Data transmit and Step control

- palladium.mk
- src/main/scala/Squash.scala
- src/test/vsrc/common/SimJTAG.v
- src/test/vsrc/common/assert.v
- src/test/vsrc/common/ref.v
- src/test/vsrc/vcs/DeferredControl.v
- src/test/vsrc/vcs/top.v
We add SYNTHESIS macros around generated DPIC funcs, and TB_NO_DPIC macros around DPIC funcs in fixed vsrc of TB.
With this change, difftest with non-default GatewayConfig can run in both SYNTHESIS or not.
> Add TB_NO_DPIC/SYNTHESIS macros around all DPIC funcs

- .github/workflows/main.yml
- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
We add an parseArgs interface of difftest for style and GatewayConfig. User can pass DifftestArgs from top module which extends App trait, and it will return filter args for sequent parsing.
Now, we support use DIFFTEST_STYLE=... to specify style such as DPIC. And use DIFFTEST_CONFIG=... to specify GatewayConfig, each letter represents an optimization measure.
> Support parseArgs for GatewayConfig

- palladium.mk
- scripts/palladium/run.tcl
- scripts/palladium/run_debug.tcl
We add exit at the end of run/debug scripts to make simualation exit automatically.
And we disable gui windows for debug by default.
> palladium: fix scripts

- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/vcs/vcs_main.cpp
- src/test/csrc/verilator/emu.cpp
In batch mode, dut may point to serveral possible position of diffstate_buffer. Trap check in difftest_state also relies on correct dut position. So we should set dut before difftest_state. 
Previously we set dut only when difftest_step, however even disable diff(difftest without proxy), we should also set correct dut ptr. So we seperate the logic into difftest_set_dut for both diff/no-diff, and difftest_step will also call it. Same change applys for both simv and emu.
This problem is hidden before, because trap may be check by next step of same batch occasionally. Failure occus when trap happens at last step of batch.
> simv, emu: set dut before checking difftest_state

- src/test/csrc/difftest/difftest.cpp
The default running status val is -1 for emu, 0 for simv. difftest_nstep perform n step comparison for emu, it should return STATE_RUNNING instead of 0 by defualt.
We fix the problem caused by PR(https://github.com/OpenXiangShan/difftest/pull/308)
> emu: fix default return val of difftest_nstep

- src/main/scala/common/LogPerfControl.scala
- src/main/scala/util/DataMirror.scala
This commit brings a DataMirror in the difftest.util package. It now includes a method called isVisible which returns the visibility of a Data object, which was originally brought into Chisel 6.1.0 for the first time.
Since this method does not exist in older versions of Chisel, and DiffTest must be compatible with legacy versions of Chisel, we use Scala reflection features to load this method dynamically. If not found, this method always returns false.
> Add the reflective DataMirror for future methods

- src/test/csrc/vcs/vcs_main.cpp
/dev/zero can be seen as a file with only NULL. This change enable us to use only +flash to set workload for bootrom(flash).
> simv: add default /dev/zero for +workload

- Makefile
- palladium.mk
- src/test/csrc/common/ram.cpp
- src/test/csrc/vcs/vcs_main.cpp
- src/test/vsrc/vcs/top.v
Support for enabling dramsim3 programs to run on Paradine. DRAMSIM3_HOME Note: Recompile dramsim3 on Paladin and set DRAMSIM3_HOME, then add DRAMSIM3_HOME to LD_LIBRARY_PATH so that it links to the dynamic library correctly
> vcs: add dramsim on emu run

- src/test/csrc/difftest/difftest.cpp
Previously the instruction commit checker loops over the commit slots and breaks the loop at any invalid slot. This avoids checking further slots and may have better performance.
However, if the design-under-test does not commit instructions one by one, the checker may fail to locate the valid instructions.
This commit fixes it by checking every commit slot.
> difftest: check every instruction commit slot

- palladium.mk
Previous change https://github.com/OpenXiangShan/difftest/pull/312 has an extra space, which cause error in path parsing, this change fixs it.
The usage of subst is $(subst \<from\>,\<to\>,\<text\>), redundant space is not allowed.
> Fix extra space of Palladium CFLAGS for path parsing

- .github/workflows/main.yml
- scripts/palladium/argConfigs.qel
- src/main/scala/Batch.scala
- src/main/scala/Gateway.scala
- src/main/scala/common/LogPerfControl.scala
- src/test/vsrc/vcs/top.v
We will dump built-in Perf for difftest at the end of simulation. These printfs can be controled by difftest_perfCtrl_dump.
For emu, we call `Emulator::trigger_stat_dump`. For simv, we raise difftest_perfCtrl_dump when simv_result is not zero.
> Add built-in Perf for difftest

- src/test/csrc/common/ram.cpp
- src/test/csrc/common/ram.h
- src/test/csrc/vcs/vcs_main.cpp
- src/test/csrc/verilator/emu.cpp
- src/test/vsrc/vcs/top.v
The mobile gcpt overlay function becomes public so that it can also be used on the vcs Paladin
> ram: add gcpt-restore option for VCS

- src/test/csrc/vcs/vcs_main.cpp
The override gcpt_restore operation should be performed before difftest is initialized, otherwise the override cannot be synchronized to the dut
> fix: gcpt over

- .github/workflows/main.yml
- config/config.h
- src/main/scala/Bundles.scala
- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- src/main/scala/Replay.scala
- src/main/scala/Squash.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
We seperate Replay feature for better structure. Signal in_replay will mark trace as replay or not, replayed trace will not be squashed. And we will record squashed range between trace_head and trace_tail, see squash function of DiffTraceInfo. In the future, Replay may support not only Squashed, but also Compress, etc.
This change also provides better flexibility for optimization. It will generated Cpp declaration depends on result of Gateway.
> Replay: seperate from Squash

- src/test/csrc/verilator/emu.cpp
- src/test/csrc/verilator/emu.h
Some signals need more than 10 posedges to reach a stable state. We may increase the reset cycles to 50 posedges, which is the same as what vcs is doing.
> emu: increase reset cycles in verilator

- src/test/csrc/common/device.cpp
- src/test/csrc/common/device.h
- src/test/csrc/common/sdcard.cpp
- src/test/csrc/common/uart.cpp
- src/test/csrc/common/vga.cpp
- src/test/csrc/vcs/vcs_main.cpp
Used to release peripherals upon reset
> vcs: add finish_device for simv_finish

- src/main/scala/Difftest.scala
- src/main/scala/Squash.scala
We seperate DiffTestBundles into REF/GoldenMem, tick of Bundle will only affected by it's Group. Default Group is REF. Note some bundle will have several Group, because it will affect both REF and GoldenMem state. Bundles allowed to be dropped will ticked incidentially when it's Group tick.
We also add built-in perf to count the tick cause of each Group.
> Squash: tick squashed state independently between Groups

- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/vcs/vcs_main.cpp
- src/test/vsrc/vcs/top.v
when the commit PC is same value as the tracking PC, print the clock cycle. 
Sometimes the result is inaccurate for branch instruction and fused instruction. 
When multiple instructions are committed in a single cycle, the commit PC is inferred from the dut->commit[0].pc at the beginning of each cycle and the number of instructions has been committed in the current cycle.
> vcs: support track pc

- src/main/scala/Batch.scala
- src/main/scala/DPIC.scala
- src/main/scala/Gateway.scala
Previous we give each bundle a different delay to collect valid value by Pipeline.
This change process bundles of same class in parallel, because offset is easy to count, and it will reduce stages in pipeline to reduces regs.
We also sort bundles by width, giving larger bundle less delay for less reg. And add `num` to info, which will reduce info costs with multiple bundle of same class.
> Batch: pack DPIC with hybird parallel and pipeline

- .github/workflows/main.yml
- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- src/main/scala/Squash.scala
Now we use Queue to buffer StoreEvent, avoid too many squash tick
caused by it. This bundle will only compare store actions betweens
DUT and REF, no other bundles depends on it, which enable us to buffer
it.
Another bundle causing many ticks is Sbuffer, for it will update
GoldenMem, and other bundle related will affected by it. Now we still
cannot buffer and submitted such bundle together.
> Squash: use Queue to buffer unsquashed Bundle

- verilator.mk
Verilator v5.024 introduces stats reports for both verilation and simulation. These reports are never expected to be useful for normal users but brings annoying prints. We are disabling them by default.
For advanced users, they should remove the `--quiet-stats` option manually in the Makefile.
See https://github.com/verilator/verilator/issues/4909 and https://github.com/verilator/verilator/pull/5018.
> verilator: be quiet for stats

- src/test/csrc/common/perf.cpp
- src/test/csrc/common/perf.h
- src/test/csrc/difftest/difftest.cpp
As test in Palladium, Speed calculate by Time and CycleCnt is very close to Palladium report. We add this platform-independent report here.
> Perf: report Simulation speed when finish

- src/test/csrc/vcs/vcs_main.cpp
- src/test/vsrc/vcs/top.v
When the simulation exits abnormally, we should let the user know there're failures.
> vcs: exit with $fatal for errors

- src/test/csrc/vcs/vcs_main.cpp
This change is corresponding to difftest_init.
> vcs: call difftest_finish also when no-diff

- scripts/palladium/argConfigs.qel
- src/test/vsrc/vcs/top.v
Palladium disallow empty argument for $fatal(). We remove bracket and declare it as TB_IMPORT
> vcs: remove bracket of $fatal

- src/main/scala/Bundles.scala
- src/test/csrc/difftest/difftest.cpp
New LoadEvent bundle fit XiangShan since commt [0c00289](https://github.com/OpenXiangShan/XiangShan/commit/0c002899437318e70e22fef7cb1df29f0fa8ca68)
As XiangShan change the encoding of fuType, two more decoupled singal isAtomic and isLoad is added to distinguash different load event, replacing the whole fuType
> LoadEvent: replace fuType with isAtomic and isLoad

- src/test/csrc/verilator/emu.cpp
> emu: fix the missing `-F` option in help

- src/test/vsrc/vcs/top.v
I want to be able to use the max-instrs option to exit the program without ENABLE_WORKLOAD_SWITCH enabled
> vcs: fix the support for --max-instrs

- src/test/csrc/vcs/vcs_main.cpp
- src/test/vsrc/vcs/top.v
Since we have different sizes of gcpt that need to be replaced in order to recover different core numbers or instruction sets with new checkpoints, we need to add this feature in order to support different sizes of gcpt
> vcs: add set_overwrite_nbytes of gcpt.bin

- Makefile
- libso.mk
This commit adds support for using difftest as a lib to simulate with XS.
For now, it works both on VCS and Palladium.
use "make difftest-so" to generate libdifftest.so and link it when compiling your design.
> Make: add support for compiling difftest as a lib.so

- config/config.h
MultiCore test in XiangShan will failed with origin small stack size. So there larges the stack size.
> stack: large the size

- src/main/scala/Difftest.scala
In difftest, CSR is only valid and used when instrcommit or exception. CSR value maybe invalid in other time, so we will only squash HCSR/VecCSR when there is also commit/event in this cycle.
> Squash: add SquashDependency for HCSR/VecCSR

- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/vcs/vcs_main.cpp
When exiting the program using max_instrs, ensure that each core runs to the corresponding number of instructions, and add the core id when printing the IPC
> vcs: check max-instrs for every cpu core

- config/config.h
- src/test/csrc/verilator/emu.cpp
Verilator v5.026 comes with an automated stack resizer (see https://github.com/verilator/verilator/pull/5104) for various verilated models. The stack size will be set implicitly in the constructor of the verilated design based on an estimated stack size requirement.
Thus, we comment out the `setrlimit` lines for newer version of Verilator. They will use the estimated stack size instead of the predetermined constant value.
> emu: update the stack size only for legacy Verilator

- .github/workflows/main.yml
- Makefile
This commit changes the default target of make to difftest_verilog.
The previous default target is emu. However, emu is for only the Verilator target, one of the three supported simulation platforms.
To make the default target clearer, we change the default target to difftest_verilog. It generates example difftest design-under-test interfaces and C++ files. Using this main target, user may connect their own design (maybe in Verilog) to difftest for simulation.
> Makefile: set difftest_verilog the default target

- verilator.mk
verilator.mk checks the existence of ccache and use it when possible. However, on some OS platforms, such as CentOS, this checker may cause warning messages if ccache does not exist. Since this checker is always called even when the user is not building Verilator targets, the warning message seems confused for users.
We avoid this message by redirecting the stderr to /dev/null.
> Avoid warning messages when ccache does not exist

- README.md
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/plugin/spikedasm/spikedasm.cpp
- src/test/csrc/plugin/spikedasm/spikedasm.h
We remove unnecessary extra logic to dasm the instruction string. The execution speed is improved by 1.78X.
We also add redirection for stderr when checking the existence of spike-dasm. This should avoid the not-found warning when running the simulation.
After this change, the user may not be aware of the spike-dasm plugin for disassembly the instruction. Therefore, we update the README as well.
> spike-dasm: performance improvement

- Makefile
- verilator.mk
This results in the following output.
> misc: use time -v in time log

- verilator.mk
Verilator's default OPT_SLOW is empty, which defaults to -O2 in nix environment.
This PR explicitly set OPT_SLOW to -O0, which will reduce total CPU time when compiling C++ to binary.
A typical cli args compiling XiangShan in nix is as follows:
```
-fPIC
-Wformat
-Wformat-security
-Werror=format-security
-fstack-protector-strong
--param
ssp-buffer-size=4
-O2
-U_FORTIFY_SOURCE
-fwrapv
-target
x86_64-unknown-linux-gnu
-I.
-MMD
-I/nix/store/8ig1aks3glkph3y165gzlgiwsxnagx8w-verilator-5.022/share/verilator/include
-I/nix/store/8ig1aks3glkph3y165gzlgiwsxnagx8w-verilator-5.022/share/verilator/include/vltstd
-DVM_COVERAGE=0
-DVM_SC=0
-DVM_TRACE=1
-DVM_TRACE_FST=1
-DVM_TRACE_VCD=0
-faligned-new
-fbracket-depth=4096
-fcf-protection=none
-Qunused-arguments
-Wno-bool-operation
-Wno-c++11-narrowing …
```
> verilator: use -O0 in OPT_SLOW

- verilator.mk
We avoid implicitly and by default using ccache because it is not that useful for general users. For advanced users familiar with ccache, it can still be enabled with OBJCACHE=ccache.
> verilator.mk: remove ccache checker

- README.md
- src/main/scala/Difftest.scala
Enable difftest without optional DifftestTopIO by add extra parameter `createTopIO: Boolean = true` to `DifftestModule.finish()`.
Chisel design can set this parameter to `false` to skip the creation of DifftestTopIO and use it in non-module context.
> difftest: Enable difftest without optional DifftestTopIO

- src/main/scala/Gateway.scala
Multicore support for hasdut added on Paladin or VCS
> difftest: writeback support for dual core 

- src/test/csrc/common/common.cpp
- src/test/vsrc/common/assert.v
This commit adds the xs_assert_v2 and introduces the `filename` argument to show which file the assertion line lies. This is very useful if the design is generated using `--split-verilog`.
For backward compatibility, xs_assert is preserved.
> assert: add v2 to include filename information

- src/test/csrc/common/common.cpp
- src/test/csrc/common/common.h
- src/test/csrc/common/main.cpp
This commit fixes the assertion control logic by introducing a init function without setting assertion_count to 0. The user may manually call common_enable_assert to enable assertions.
Previously we are checking whether the assertions are allowed by negative assert_count values. However, this variable is incorrectly set to zero during common_init.
> common: fix the assertion control logic

- src/main/scala/Batch.scala
- src/main/scala/Difftest.scala
We use delayer to delay signal for several cycles. Now we can use Reg or Mem to implement it. In some case like Palladium, Mem will be treated as RAM, it will save more gates than register.
> Delayer: optionally use Mem to reduce gates

- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
In difftest cpp code, wb_int will only be synced as get_commit_data when commit with skip(MMIO) or Load, and record to commit instr trace. Since there are multiple DUT buffer in software side, and wb_int transferred and used not in the same buffer, so we buffer valid wb_int until instr commit.
This change will fix related bug when enable complete difftest with multicore.
> difftest: buffer wb_int until instr commit for multiple DUT buffer

- src/main/scala/Squash.scala
- src/test/csrc/difftest/difftest.cpp
Load is related to reg writeback for goldenMem and regfile compare. Previous we ignore load for singleCore for better squash rate. But currently load is unsquash, because different core relys on load to pass reg data from other cores. We use load data to change REF model regfile.
And we also reset isLoad and isAtomic after use. These signals act as if-cond, and outdated ones will result in wrong reg copy.
> difftest: force load unsquash for multicore, reset after use

- .github/workflows/main.yml
- verilator.mk
This commit add PGO_CFLAGS and PGO_LDFLAGS when calling verilator to generate Makefile. And add script to build PGO for both GCC and LLVM.
The following is the usage of PGO:
```shell
make emu MFC=1 EMU_THREADS=16 NUM_CORES=1 PGO_WORKLOAD=`realpath ready-to-run/coremark-2-iteration.bin` LLVM_PROFDATA=llvm-profdata -j `nproc`
```
Note: The LLVM_PROFDATA is hard to detect if multiple versions of LLVM are installed. An example is that on Debian, we can install different versions of LLVM and use a version with suffixes like `clang++-18`. The LLVM_PROFDATA should be set to the correct version like `llvm-profdata-18` in this case.
If the compiler of verilator is GCC, we should not use LLVM_PROFDATA:
```shell
make emu MFC=1 EMU_THREADS=16 NUM_CORES=1 PGO_WORKLOAD=`realpath …
```
> verilator.mk: Add support for PGO

- src/main/scala/Bundles.scala
- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- src/test/csrc/difftest/difftest.h
We use physical Register WriteBack for loadEvent and MMIO access, and record commit Data in Commit Instr Trace. As there are multiple DUT buffer in software side, WriteBacks transferred and used may not in same cycle, so we buffer corresponding wb data until instrCommit.
As writeBacks only used in get_commit_data, and comes from int/vec/fp, we preprocess commitData in hardware side, and submit along with InstrCommit. This change will fix error of fpWriteBacks, and also help simplify logic of Load Squash.
> CommitData: preprocess data in Hardware, submit with InstrCommit

- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
Previously we bind load_check with InstrCommit. For Squash and acceleration, we move Load check to a single Function.
> difftest: move check of LoadEvent to do_load_check

- .github/workflows/main.yml
- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- src/main/scala/Squash.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
Some unsquash event, such as LoadEvent and StoreEvent, will seriously hinder squash of related diffstate. We submit such event independently and queue them in software side with SquashStamp.
There queued event will be checked when num_commit meets stamp, resuming check order of different squashed event.
> SquashQueue: queue unsquash event and check against stamp

- Makefile
For Verilog users, please explicitly use RTL_SUFFIX=v when calling difftest.
> Makefile: set default RTL_SUFFIX to sv

- verilator.mk
This is mainly for `ClockGate.v`. Previously, it is written as:
``` v
module ClockGate (
input  wire TE,
input  wire E,
input  wire CK,
output wire Q
);
wire clk_en;
reg  clk_en_reg;
assign clk_en = E | TE;
`ifdef VCS
// code A
always @(CK or clk_en) begin
if (CK == 1'b0)
clk_en_reg <= clk_en;
end
`else
`ifdef VERILATOR_5
// code A
always @(CK or clk_en) begin
if (CK == 1'b0)
clk_en_reg <= clk_en;
end
`else
// code B
always @(posedge CK) 
begin
clk_en_reg = clk_en;
end
`endif // VERILATOR_5
`endif // VCS
assign Q = CK & clk_en_reg;
endmodule
```
Actually, only verilator 4 should use code B. All other tested platforms like verilator 5, vcs and vivado should use code A. It is better to write ClockGate as:
``` v
module ClockGate (
input  wire TE,
input  wire E,
input  wire CK,
output wire Q …
```
> verilator.mk: define `VERILATOR_LEGACY` for version less than 5

- src/main/scala/util/VerificationExtractor.scala
We add a VerificationExtractor transform with an annotation named VerificationExtractorSink to support synthesizable assertions.
First, the user should annotate a sink Bool variable to let the transform know that it should do wiring for all assertions. Second, the transform collects all assertions (firrtl.ir.Verification) from the circuit and adds SourceAnnotation for wiring. Third, in the sink module, the transform creates Cat and orR nodes to compute a Bool value for the annotated assertion sink.
The user should 1) annotate the sink Bool using the function VerificationExtractor.sink, and 2) add VerificationExtractor to the build dependecy as one of the transforms.
This transform does not support Chisel 3.x now and in the future. To allow compiling the code using Chisel 3.x, we use Scala …
> util: add support for synthesizable assertions

- src/test/csrc/plugin/runahead/memdep.h
Missing ```#include <deque>``` in memdep.h:
* Failing in some ```gcc``` compiling scenarios
> runahead: fixed missing <deque> include in memdep

- src/test/csrc/verilator/emu.cpp
Three cycles of vcd dumping confliction after reset with **```--dump-wave-full```** in current implementation.
> emu: fix cycle conflict in full-wave dumping

- src/main/scala/Gateway.scala
- src/main/scala/common/WiringControl.scala
- src/main/scala/util/DataMirror.scala
By default we use BoringUtils.addSink/Source to collect Difftest Signals from DUT to DifftestEndpoint, which will introduce extra IOs to each Layer of DUT Module.
By BoringUtils.tapAndRead, we can use Difftest Signals with Cross Module Reference(like SimTop.xxx.yyy) instead of explicit IO. This feature enabled by GatewayConfig.hierarchicalWiring, and requires addSource before addSink.
Since BoringUtils.tapAndRead does not exists in older version of Chisel, we use Scala reflection features to load it dynamically.
> Wiring: support hierarchical source/sink without extra IOs 

- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- src/test/csrc/verilator/emu.cpp
- src/test/vsrc/vcs/DifftestEndpoint.v
- src/test/vsrc/vcs/top.v
This commit adds the exit output to the top-level IO of difftest. When it is a non-zero value, the simulation should exit. When all bits are ones, the simulation exits normally. Otherwise, it indicates there are some errors in the circuit.
> top: add the exit output to exit the simulation

- src/main/scala/Batch.scala
- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- src/main/scala/util/Delayer.scala
With Hierarchical Wiring (require Chisel6 and difftestConfig H), we can collect signals from DUT to Difftest, like SimTop.xx.yy.
Previous we instantiate Delayer before addSource, the Delayer is instantiated inside DUT. This change move it after addSource, so Design and Verification code can be seperated when needEndpoint and Hierarchical Wiring.
When Hierarchical wiring, We use Endpoint by default.
> difftest: instantiate Delayer inside Endpiont

- src/main/scala/Bundles.scala
At somewhere like AM, the return value of the main function is also used as the trap value ([trm.c](https://github.com/OpenXiangShan/nexus-am/blob/28c275b0ea38a341e6ce158d631bb41109863dd2/am/src/noop/isa/riscv/trm.c#L34)). However, currently, our trap value is only 3-bit-wide, which may lead to the situation where returning a non-zero value in the main function but difftest still HIT GOOD TRAP.
In fact, some of our users have encountered this issue while using AM to write test cases, and they hope that we can expand the width of the trap value. I believe this requirement is reasonable as it can help to use different return values to determine the accurate location and the specific reason of an abnormal exit.
Regarding the potential performance impact caused by expanding the bit width of …
> TrapEvent: enlarge width of trapcode to 32

- src/test/csrc/common/lightsss.cpp
- src/test/csrc/common/lightsss.h
- src/test/csrc/verilator/emu.cpp
Current Problem:
1. Non-oldest child process call exit(0) to kill itself. And the parent child doesn't waitpid it.
2. The non-oldest child gets stucked, and exit(0) is failed to over.
3. There 'whole' program can not stop correctly or there will be a zombie process.
Solution: 
The parent manually kills the non-oldest child processes in wake-up just like it does in do-fork.
> lightsss: parent manually kills child that not the oldest when wake up

- Makefile
- src/main/scala/Difftest.scala
- src/test/scala/DifftestMain.scala
In acclerated and multi-core verification cases, we need to adjust or build Difftest's Hardware side seperately.
We use json to record Difftest apply and finish Info of DUT. Then difftest can rebuild for single or multi cores according to Profile.
> difftest: support dump and rebuild by profile

- src/main/scala/Batch.scala
- src/main/scala/Bundles.scala
- src/main/scala/DPIC.scala
- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- src/main/scala/Squash.scala
- src/main/scala/Validate.scala
Previous we transmit all DiffState without hasValid when some DiffState valid in same cycle. However, when Squash enabled, some State without hasValid can be validated with special condition. As Submit times of State with SquashQueue is much greater than others, validated will greatly reduce submit times of Stata without hasValid.
Previous we also use do_squash and squashDependency to filter invalid CSR value. This change rename squashDependency to updateDependency, and only validate CSR when commit and event. So we remove do_squash.
As Trapevent will also be checked for instrs Exceed, we transmit it when validated, rather than just hasTrap or hasWFI.
> Validate: append valid to DifftestBundle

- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
Sometimes the dut or ref will wrongly jump to a pc, and if their reg state still match in the next instructions, this will make debugging very difficult. So I add the comparison to the pc.
> pc: add compare for the first instr pc of a commit group.

- .github/workflows/main.yml
- src/main/scala/Batch.scala
- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- src/main/scala/Trace.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/difftest/difftrace.cpp
- src/test/csrc/difftest/difftrace.h
- src/test/csrc/verilator/emu.cpp
- src/test/vsrc/vcs/DifftestEndpoint.v
Trace module will dump trace of IOs between DUT and difftest. With trace file and json profile, we can drive difftest without DUT, which will speed up repeated simulation without DUT modification, and support difftest modification and iteration.
Note we padding 100 trace at the end of traceFile when dumping, because when enable some features for acceleration, Difftest may finish comparision within some cycles after loading trace.
> Trace: support dump and load trace of difftest IOs

- src/test/csrc/common/SimJTAG.cpp
- src/test/csrc/common/remote_bitbang.h
- src/test/csrc/vcs/vcs_main.cpp
- src/test/vsrc/vcs/DifftestEndpoint.v
The JTAG driver is packaged within the difftest shared object (.so) file, initialized with dpic, allowing the use of simjtag in the VCS environment.
> difftest:Surrport VCS use sim-jtag

- src/main/scala/DPIC.scala
- src/main/scala/Gateway.scala
Privious when InternalStep is defined, we pass difftest_step to Batch DPIC instead of tb_top, thus putting transmission and comparision together.
This change pass step to tb_top all the time, which can indicate Difftest check triggered.
> Difftest: always pass step to tb_top

- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/plugin/runahead/runahead.cpp
- src/test/csrc/vcs/vcs_main.cpp
- src/test/csrc/verilator/emu.cpp
- src/test/vsrc/vcs/DifftestEndpoint.v
Since difftest step function may not be called every cycle, we use cycleCnt recorded in trapEvent instead of ticks, to check timeout for Instr commits.
However, commit timeout will only be checked when difftest checks, which is triggered by difftest_step. We also check if step is 0 for more than stuck_limit for both vcs and emu.
> Difftest: check timeout for both commit and step

- src/main/scala/Bundles.scala
TrapEvent may not raise hasTrap when any other bundle valid, so we recover needUpdate to mark there is valid TrapEvent at this cycle.
In Validate, we use getValid to mark valid for single bundle, and needUpdate to mark valid for this cycle. We will transmit trapEvent when hasTrap, or other bundles valid.
> Validate: recover needUpdate for TrapEvent

- .github/workflows/main.yml
- Makefile
- src/test/csrc/difftest/difftrace.cpp
- src/test/csrc/difftest/difftrace.h
Adding the difftest trace feature enables ZSTD for streaming compression, which compresses the trace volume by about 98%, enabling printing more cycle traces to disk
> iotrace: add iotrace dump and load zstd compress support

- src/test/csrc/common/golden.h
- src/test/csrc/difftest/difftest.cpp
Also refactor page table walker level:
previous (only support Sv39):
level 0 -> 1GB page
level 1 -> 2MB page
level 2 -> 4KB page
current (support Sv39, Sv48, and future extension) Sv48 -> maxlevel = 3, Sv39 -> maxlevel = 2
level 3 -> 512GB page
level 2 -> 1GB page
level 1 -> 2MB page
level 0 -> 4KB page
> Difftest, mmu: Support Sv48 & Sv48x4 ptw check

- src/test/csrc/verilator/emu.cpp
This is required in older versions of Verilator and can be removed now.
We don't need to override the simulation timestamp.
> emu: remove the sc_time_stamp function

- src/test/csrc/common/ram.cpp
- src/test/csrc/common/ram.h
- src/test/csrc/vcs/vcs_main.cpp
- src/test/csrc/verilator/emu.cpp
- src/test/csrc/verilator/emu.h
add argument --dramsim3-ini to pass the dramsim3 config file, no need to modify makefile and recompile
> misc: add argument --dramsim3-ini to set dramsim3 config file

- src/test/csrc/common/golden.h
- src/test/csrc/difftest/difftest.cpp
As a legacy issue of supporting Sv48, the default level of do_s2xlate when mode=0 is incorrect. Also, for only VS stage case (onlyS1), it should not do_s2xlate at all. This patch fixes these problems.
> fix(l1tlb_check): correct the check for only VS stage

- src/test/csrc/vcs/vcs_main.cpp
- src/test/csrc/verilator/emu.cpp
- src/test/csrc/verilator/emu.h
- src/test/vsrc/vcs/DifftestEndpoint.v
New versions of gcpt allow you to set oversize automatically. if you don't specify size manually, gcpt will look for an oversize flag，on vcs/palldium  using --set_overwrite_autoset enable auto set oversize，on emu using --overwrite-auto
> difftest: automatically set the overwrite-size of new gpct

- config/config.h
> fix(config): allow 8GB memory as default for unknown CPUs

- README.md
- src/main/scala/Bundles.scala
- src/main/scala/Difftest.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/difftest/refproxy.h
- src/test/scala/DifftestTop.scala
This PR adds support for non-register interrupts pending to copy the interrupt to NEMU. 
The interrupts come from Count overflow and Platform-Level Interrupt Controller such as PLIC, CLINT, IMSIC. 
Thus, we could diff xip csr registers of XiangShan and NEMU.
> fix(csr): add support non-register interrupts pending

- .github/workflows/main.yml
- src/main/scala/Batch.scala
- src/main/scala/DPIC.scala
- src/main/scala/Gateway.scala
- src/test/csrc/common/perf.cpp
- src/test/csrc/common/perf.h
To facilitate Batch migration between DPIC and PCIe, we pack Batch param to an aligned array, and parse it inside software.
In transmission, we only need to pass single hardware data, as svBitVecVal[] or uint8_t[], and then view it as generated struct in software.
Note we put step inside BatchInfo and call simv_nstep inside, Step will be also exposed to Top all the time for Verilator and Timeout Check.
> Batch: pack Batch param to facilitate migration between DPIC/PCIe

- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/refproxy.h
- src/test/csrc/verilator/emu.cpp
When initializing REF's memory, call mem_init function. If REF provides ref_memcpy_init, use it. If not, use ref_memcpy.
> feat(mem): add optional ref func `ref_memcpy_init`

- src/main/scala/Bundles.scala
- src/main/scala/Difftest.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/scala/DifftestTop.scala
When the DUT executes a cbo.inval, a set is used to record its cacheline address.
Later, if there is a data mismatch between DUT and GoldenMem in the address space operated by the cbo.inval instruction, the Pmem of REF and GoldenMem will be directly updated using the data of DUT.
> fix(cmo): Support difftest for cbo.inval instruction

- src/main/scala/Bundles.scala
- src/test/csrc/difftest/refproxy.h
In our new trigger solution, we donot need implement tcontrol.
> fix(trigger): no need to implement tcontrol in XiangShan trigger

- src/main/scala/Batch.scala
- src/main/scala/DPIC.scala
- src/main/scala/Gateway.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/vcs/vcs_main.cpp
Previously, we view data collected from same cycle as a whole, end batch assembling when step data longer than available space. It results in bubble in transmission, and cannot handle situation when step data longer than Max width in a single transmission.
This change support spliting step data according to collector, appending part of data to output and updating remained to state. To shorten logic length, we divide complex logic to three stage.
Note step data may be splited to different batch func, and should be read as a whole, so we avoid buffer-zone switch when batch enabled.
> Batch: support data split to reduce transmission bubble

- src/main/scala/Batch.scala
- src/main/scala/Squash.scala
Commit the remaining cache for squash and batch when the cpu has not committed an instruction for a long time
> difftest: submit buffered data in Squash/Batch when timeout

- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- src/test/scala/DifftestTop.scala
When using json to generate difftest, it is necessary to manually connect difftest in ST environment. Now through the generated svh file, it is possible to automatically connect the difftest interface in ST environment without being affected by interface changes
> difftest: endpoint connection optimization

- src/main/scala/Difftest.scala
When Squash enabled, previous squashed instrCommit may be submitted with new-coming updated ArchRegState, which results in reg mismatch with REF.
In difftest software side, we will only use ArchRegState when instrCommit or event (progress = true in code), so we add updateDependency for ArchRegState to ensure using corresponding ones with squashed commits, just like we add for CSR before.
> Validate: update ArchRegState only when commit or event

- README.md
- src/main/scala/Bundles.scala
- src/main/scala/Difftest.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/scala/DifftestTop.scala
This pr raise critical-error in difftest when XiangShan issues a critical-error signal.
The `critical-error` state is defined in the `smdbltrp` extension. This extension specifies that when the `critical-error` signal is asserted, the CPU should halt execution. This PR implements a method for stopping execution in simulation mode, where difftest halts by triggering an `abort`.
In the future, an option to enter debug mode rather than directly halting the CPU will be introduced for handling `critical-error`. This incoming change won’t require modifications to the difftest framework; Xiangshan will only need to control it through an  `valid` signal.
> feat(dbltrp): add support for critical-error

- README.md
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/refproxy.h
* When both RTL and NEMU report a critical-error, the hardware behavior is considered correct. Upon detecting a critical-error, it should indicate a "good trap."
* If they do not report simultaneously, it results in a diff error and triggers an abort.
> fix(dbltrp): critical-error is not treated as diff error

- src/main/scala/Bundles.scala
- src/test/csrc/difftest/difftest.h
* All trap codes outside the enumeration range will be converted to `bad_trap`
> fix(xstrap): expand trapcode to 64bit

- src/main/scala/Difftest.scala
- src/main/scala/util/Profile.scala
- src/test/scala/DifftestTop.scala
These functions have been implemented before. This commit organizes them together to a separate Scala file.
> Profile: add public APIs for creating and dumping

- src/main/scala/util/Profile.scala
This is possible when there are not any connected difftest interfaces.
> fix(profile): allow numCores to be zero

- src/test/csrc/common/elfloader.cpp
I've added a small bug when counting the total bytes written during elf loading. The problem is that we are unpacking the elf and we need to calculate the total size of the resulting memory image, not the "compressed" bytes written.
> fix(mem): Fix elf loading byte counting

- README.md
- src/main/scala/Bundles.scala
- src/main/scala/Difftest.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/difftest/refproxy.h
- src/test/scala/DifftestTop.scala
In order for NEMU to use the value of the `xtopi` register for interrupt handling, we need to update the `xtopi` register in NEMU. Since NEMU does not support the out-of-core part of AIA, we need to use the value of `xtopei` when updating `xtopi`, so we pass `xtopei` through the difftest framework.
> fix(aia): add support for aia xtopei csr

- src/test/csrc/common/SimJTAG.cpp
- src/test/csrc/common/SimJTAG.h
- src/test/csrc/common/common.cpp
- src/test/csrc/common/common.h
- src/test/csrc/common/device.cpp
- src/test/csrc/common/flash.cpp
- src/test/csrc/common/flash.h
- src/test/csrc/common/golden.cpp
- src/test/csrc/common/golden.h
- src/test/csrc/common/ram.cpp
- src/test/csrc/common/ram.h
- src/test/csrc/common/sdcard.cpp
- src/test/csrc/common/uart.cpp
- src/test/csrc/common/uart.h
- src/test/csrc/common/vga.cpp
- src/test/csrc/common/vga.h
Previous we declare and implement extern func in cpp file directly, and call by import DPIC in verilog or another extern declaration in other cpp files.
However, when supporting gsim, too many extern declaration and calls in different files make it hard to link and locate, causing undefined reference error.
This change move declaration of extern func to header, add we will include header while generating extern-module func.
> difftest: move declaration of extern func to header

- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
When squashQueue enabled, load/store event may be submitted ahead and buffered in queue before squashed instrs commit along with replay info. So when we recover snapshot and start replaying, we need clear queue, submit and process load/store again.
This change also ensure least report of squashed error before replay, and check if DUT run out of replay range. Also, seperate original step() logic to private do_step(), keep same call interface
> Replay: clear buffered queue, ensure least error report

- src/main/scala/Gateway.scala
When using FPGA diff, the batch data interface is brought to the gateway top-level
Co-authored-by: zhangshoulin [zzsl1117@gs.zzu.edu.cn](mailto:zzsl1117@gs.zzu.edu.cn)
> Batch: expose extra GatewayIO for FPGA

- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/refproxy.h
Currently, `skip_one` only handles scalar cases. When a floating-point skip_one occurs, the value of the floating-point register is incorrectly synchronized to the scalar register. We have fixed this.
After the modification, we can correctly handle scalar and floating-point skips. However, vector skips will not be allowed, so an assert will be raised when a vector triggers a skip.
Currently, our framework cannot correctly synchronise the data in the vector register. After subsequent discussions, we will add support for this, and this commit will first fix the bug where the floating-point register cannot be correctly synchronised.
---
For reference, the XiangShan processor should never under normal circumstances generate a skip vector, so it is acceptable to add an assert in this place, …
> fix(skip_one): fix floating-point `skip_one` logic

- src/test/csrc/verilator/emu.cpp
- src/test/csrc/verilator/emu.h
- For large designs, we need large intervals as the simulation speed slows down
- Small intervals may bring notable overheads for large footprint workloads
> emu: increase default LightSSS interval to 10 seconds

- src/test/csrc/common/flash.cpp
- src/test/csrc/common/flash.h
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/refproxy.cpp
- src/test/csrc/difftest/refproxy.h
This new API accepts the first argument as a pointer to the flash image in memory instead of a string pointer to the flash filename.
> feat(ref): add the optional load_flash_bin_v2 API

- src/test/csrc/common/flash.cpp
- src/test/csrc/common/flash.h
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/refproxy.cpp
- src/test/csrc/difftest/refproxy.h
When the flash image is not specified explicitly, load_flash_bin does not know the initial values of flash. Currently the REF loads the same initial instructions as DiffTest, which is not a good practice.
> feat(ref): prefer using load_flash_bin_v2

- src/test/csrc/common/flash.cpp
- src/test/csrc/common/flash.h
This is not supported in some C++ standards.
> fix(flash): avoid non-trivial designated initializers

- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
This commit fixes the wrong macro that wraps the cmo.inval checkers.
> fix(difftest): wrap cmo.inval code with macros

- scripts/st_tools/interface.py
fix with incorrect text substitution ranges
> scripts: fix extra trailing comma in instantiation

- libso.mk
This patch makes two changes:
* Use `?=` rather than `=` to set var VERILATOR_ROOT.
If environment has VERILATOR_ROOT env, just use it.
* Use `--getenv` to get env var VERILATOR_ROOT.
This is much simpler and clearer. Additionally, the previous command would make mistake, if the VERILATOR_ROOT during compilation differs from the actual directory of verilator at runtime.
> build: fix VERILATOR_ROOT problem

- src/main/scala/Difftest.scala
For integration with external SoC, the NUM_CORES was not known at chisel elaboration time. Add the `#ifndef NUM_CORES` to support override core numbers at the final compile stage.
> feat(difftest): Support override NUM_CORES at compile time

- src/test/csrc/fpga/fpga_main.cpp
- src/test/csrc/fpga/xdma.h
Fixed multiple definition not compiling when enable DIFFTEST_PERFCNT
> fix(perf): avoid redundant includes and add missing finish for FPGA

- README.md
- src/main/scala/Bundles.scala
- src/main/scala/Difftest.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/difftest/refproxy.h
- src/test/scala/DifftestTop.scala
Because not only the xtopei in AIA needs to be synchronized.
Also added support for hgeip synchronization.
> fix(AIA): change DiffAIAXtopeiEvent to DiffSyncAIAEvent

- src/main/scala/common/WiringControl.scala
Currently we will add source annotation when hierarchical wiring is not enabled. Return source directly will leave source annotation along, causeing sink unresolved error in firtool
> fix(wiring): return source only when not using source annotation

- src/main/scala/Bundles.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/refproxy.h
* The current external interrupts come from two sources, `PLIC` and `IMSIC`.
* We need to distinguish the source of external interrupts in `NEMU`, so we need to separate the external interrupt source from `PLIC` or `IMSIC` in the `difftest` framework.
> fix(aia): distinguish external interrupts sources from PLIC or IMSIC

- src/test/csrc/fpga/xdma.cpp
Remove a temporary fix that was done on the FPGA to fix this issue, and fix a bug where the producer incorrectly parses data in multithreading mode
删除一个临时修复（此问题在FPGA上已修复），修复使用USE_THREAD配置运行时，生产者端进行了重复数据解析的问题
> fix(xdma): remove replicate data parsing when USE_THREAD_MEMPOOL

- src/main/scala/Batch.scala
- src/main/scala/Gateway.scala
- src/main/scala/Replay.scala
- src/main/scala/util/Lookup.scala
Previous we collect data from different groups(a group means Diffstate with same desireCppName) in pipeline (delay different groups to different stage by RegNext). And at each stage Batch will concat valid data from one group to step_data.
This change use two-stage collector to reduce gates: 
Stage1: Different groups will collect data in parallel to get tight-arrangement group_data.
Stage2: Batch will collect data from different groups in one cycle, group_vsize will be used to cut valid data from tight group_data by LookupTree, and valid data from different groups will be concated to step_data.
In pallaium, this change will reduce Batch gates from 21M to 12M. And in FPGA, XS(Basic-Diff) with ESBI config will use 80% LUT (XS needs 70% LUT itself).
> Batch: collect from different groups in one cycle to reduce gates

- src/main/scala/Preprocess.scala
After optimized by Squash, DPIC bytes of LoadEvent accounts for nearly 30% of total. However in do_load_check(difftest.cpp), LoadEvent will only be used when numCores greater than 1, so we skip LoadEvent for singleCore.
> Preprocess: skip loadEvent for single-core

- src/test/vsrc/vcs/DifftestEndpoint.sv
- vcs.mk
An additional `simv_step_event` was introduced to control the execution order of the `simv_nstep()` DPI call. The order of DPI calls in different `always` blocks is inherently unpredictable. Since `simv_nstep()` depends on the state updated by other `v_difftest_*` DPI calls, a `#0.1` delay was added to ensure that `simv_nstep()` is executed at the end of each clock posedge. This modification resolves potential timing issues caused by the implicit dependency between difftest DPI calls.
Additionally, the file extension of `DifftestEndpoint.v` was changed to `.sv`, as the `event` mechanism is a feature specific to SystemVerilog.
> vcs: Ensure correct execution order of difftest DPI calls

- src/main/scala/Batch.scala
- src/main/scala/Gateway.scala
Previous we enable splitting Batch data to handle peak data valid in same cycle (we call these data collected in same cycle Stepdata). The step data may be splitting according to remain space of Batch state, and part of them will be appended to Batch output to make full use of Batch DPIC.
However, this split strategy need some gates to handle splitting and appending behaviour. Now for FPGA, we need to reduce gates of Batch, so we disable split strategy.
According to gateCount of Palladium, disable split strategy will reduce gates of Batch from 12M to 8M (in full Difftest). And in FPGA, LUT of XS and Difftest(Basic-diff) will reduce from 81% to 77%, with XS accounts for 70% itself.
> Batch: disable split strategy for FPGA to reduce gates

- src/test/csrc/common/elfloader.cpp
The `readFromElf()` relies on all phdr entries are sorted by paddr, which is not mandatory for the ELF format. We must sort the parsed `sections` before return back to `readFromElf()`.
> fix(elfloader): Sort phdr entries by paddr before return to `readFromElf()`

- src/main/scala/Batch.scala
- src/main/scala/DPIC.scala
Previous we append BatchInterval at the head of StepInfo, using it to update index of software buffer.
This change rename BatchInterval to BatchStep, and append it to StepInfo in BatchCollector rather than BatchAssembler to simplify logic. Also, putting BatchStep at tail of StepInfo allow some operation after Batch parsing, which is needed by Incremental
transmit.
> Batch: rename BatchInterval to BatchStep, move to tail of StepInfo

- src/test/csrc/difftest/goldenmem.h
To cosim with DMA device, we need to update goldmem when a write request was initiated by the device.
> feat(difftest): Export goldmem read/update as C API for DMA cosim

- src/main/scala/Gateway.scala
When using fpga, the IO width information is exported to the macro definition file, and the info and data in the out are merged to facilitate direct connection to the transmission module
> batch: export FPGA IO width macro and merge output data for connection

- palladium.mk
It will slightly speed up the software simulation. Tested in Palladium( with Config ESBIN), time consumed by USER_CODE (including Difftest and NEMU) will reduce about 10%.
> palladium.mk: add O3 option for PLDM_CXX_FLAGS

- src/test/csrc/vcs/vcs_main.cpp
The clock and instruction counter data should be saved at the time of the warmup to calculate the IPC after the warmup，It also supports recording the warmup data of each core when multiple cores are used，and change the command print prompt when the warmup trigger is triggered to base 10
> fix: Save the clock and instruction count for the warmup

- scripts/palladium/argConfigs.qel
When we enable XSPerf for XiangShan, logPerfs will be collected to LogPerfEndpoint. Previous we map all logPerfs to GFIFO, and LogPerfEndpoint consumes abount 140M gates, more than XiangShan itself.
This change map fwrite in LogPerfEndpoint to TB_IMPORT, reducing gates from 140m to 68M.
Note we cannot map all fwrites to TB_IMPORT, as some fwrites generated by chisel assert will include complex signal, greatly increase compile time from about 4h to more than 1 day.
> palladium: map fwrite in LogPerfEndpoint to TB_IMPORT

- config/config.h
- src/main/scala/Bundles.scala
- src/main/scala/Difftest.scala
- src/main/scala/Preprocess.scala
- src/main/scala/Squash.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/difftest/refproxy.h
This commit adds vector load check.
This is mostly done in the following way:
1. checking for consistency of vector load results in dut and ref's pmem.
2. if not, then check if the vector load results in dut and golden mem are consistent.
3. if the check in (2) passes, update ref.
---
Consider the complexity and diversity of vector.
While accessing pmem in ref, a golden mem access will be performed at the same time, and the related information (addr, data) will be stored temporarily.
When you need to compare the golden mem, you will get the golden mem access result from ref via API.
When the golden mem needs to be updated, the API will ask ref to get the information (addr and data) from the stored information and write them to the golden mem.
---
**I've tested this in a number of …
> feat(load_check): add vec load check

- .github/workflows/main.yml
- src/main/scala/Bundles.scala
- src/main/scala/DPIC.scala
- src/main/scala/Delta.scala
- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- src/main/scala/util/Query.scala
This change add Delta feature to speed up difftest in Palladium/FPGA. We enable spliting bundle into elems, and only transmit non-duplicate elem through DPIC.
As we need a buffer to record base value for delta-transmission, we generate difftest-delta.h, which provides API to update delta data from elem's DPIC, and sync final data to diffState (just like non-delta transmission). Currectly we rely on Batch to ensure Delta order, which updates delta-buffer during DPIC parsing, and sync at the end of each step.
Based on Config ESBIN (enable Squash and Batch），Delta feature will reduce DPIC bytes by ~40%，which will be better without Squash or under Basic-Diff, where duplicate data from bundle like ArchReg/CSR... acounts for more proportions of DPIC bytes.
> Delta: support bundle spliting and filter duplicate elem

- src/test/csrc/common/ram.cpp
- src/test/csrc/common/ram.h
- src/test/csrc/vcs/vcs_main.cpp
- src/test/csrc/verilator/emu.cpp
- src/test/csrc/verilator/emu.h
Add parameter --dramsim3-outdir
> feat(difftest): add output optional parameter for dramsim3

- src/test/csrc/common/mpool.cpp
- src/test/csrc/common/mpool.h
- src/test/csrc/fpga/xdma.cpp
Since the overhead per operation is not large, mutexes are replaced by lighter locks. At the same time, by removing cv_wait from the function that controls group offset, the locks that are no longer needed are removed, which improves the processing bandwidth of mempool from  16161MB/S to more than 22450MB/S (The stress test was performed on the Intel(R) Core(TM) i7-11700 platform)
> perf(fpga): use spinLock instead of mutex and delet unwanted locks

- src/test/csrc/vcs/vcs_main.cpp
In order to make the difference between final data and warmup data more clearly for users who do not know the internal code, all relevant information is added to print, which is convenient to distinguish and use according to different needs
> log(perfcnt): more perfcont print of warmup

- README.md
- src/main/scala/Bundles.scala
- src/main/scala/Difftest.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/goldenmem.cpp
- src/test/csrc/difftest/goldenmem.h
store: PBMT>0 but PMA=main-mem, this case needs to update the golden memory.
However, due to bus transmission delays, the moment when core0 receives the uncache (main-mem store) grant fire may be later than the moment when the data becomes visible to other cores. At this point, it is uncertain whether core1 has performed a load between these two moments. If such a load occurs, core1 in the DUT will read the updated data, whereas goldenmem will still hold the previous data, leading to a difftest mismatch.
Since the timing of data visibility to other cores varies across different simulators/protocols, the solution here is to set a `flag` in advance.
Specifically, after core0 commits the "store" but before the store becomes visible, such as when core0 issues an uncache (main-mem store) …
> feat(Uncache): add event and update goldenmem for some uncache cases

- src/main/scala/Replay.scala
- src/main/scala/Squash.scala
- src/test/csrc/vcs/vcs_main.cpp
- src/test/vsrc/vcs/DeferredControl.v
This change move all export DPI-C task to function for Palladim Z2. We also add a reg for result setting from software, avoid multi-driver for simv_result, thus we can enable nonBlock for vcs.
> fix(dpic): export DPIC for Palladium Z2 and vcs

- src/main/scala/Bundles.scala
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/refproxy.h
* Since NEMU does not have AIA, a set of signals are added to tell NEMU which mode to delegate interrupt processing to.
> fix(intr): add interrupt delegate

- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
This commit changes the order of displayed instructions in the bug report. Previously we are using a vector to emulate a circular queue. Now we change it to a native C++ queue.
> feat(difftest): display instructions in order

- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
* Since the hardware error exception can only be generated by XiangShan, it can be handled similarly to an interrupt — by directly forcing NEMU to trigger the corresponding exception handler.
> feat(exception): add hardware error exception

- .github/workflows/main.yml
- src/main/scala/DPIC.scala
- src/main/scala/Difftest.scala
- src/main/scala/Gateway.scala
- src/test/csrc/fpga/fpga_main.cpp
This change expose FPGA IO with finishFPGA, enabling us to wrap both DUT, Difftest, and changing DiffTestBundle Interface within the same wrapper. Only the output of Batch, with width declared at DifftestMacros.v, will be exposed to FPGA.
> FPGA: expose IO with finishFPGA

- src/test/csrc/fpga/xdma.cpp
- src/test/csrc/fpga/xdma.h
The posix_memalign request for the xdma data accept area can fix the local data offset bug in the data packet, which may be caused by the DMA requiring 4K alignment memory
> fix(XDMA): align malloc to 4K Byte for DMA receiving

- src/test/csrc/common/perf.cpp
- src/test/csrc/common/perf.h
- src/test/csrc/difftest/difftest.cpp
- src/test/csrc/difftest/difftest.h
- src/test/csrc/fpga/fpga_main.cpp
- src/test/csrc/vcs/vcs_main.cpp
- src/test/vsrc/vcs/DifftestEndpoint.sv
Previously, we use various difftest/simv/fpga_nstep functions for Verilator/VCS/FPGA, resulting in duplicated code and inconsistent simulation conditions.
For example, in the multi-core scenario, VCS/FPGA warmedup and exceed at the same number of instructions for each core, while Verilator warmup and exceed when a certain core reaching instrs.
This change reuse the common difftest_nstep as the comparison logic and aligned the simulation conditions of VCS/FPGA with those of Verilator.
We also the issues of VCS where SIMV_WARMUP did not return correctly to DUT and where the number of instructions was calculated incorrectly during soft warmup.
> refactor(difftest): reuse common nstep logic for emu/simv/fpga

- src/test/csrc/common/mpool.cpp
- src/test/csrc/common/mpool.h
- src/test/csrc/fpga/xdma.cpp
Refactored xdma_mempool to separate memory storage from sorted data indicators, making memory usage more compact and eliminating memcpy overhead.
> mpool: separate memory storage and index

- .github/workflows/main.yml
- src/test/csrc/fpga/xdma.cpp
- src/test/csrc/fpga/xdma.h
Through this optimization, the bandwidth of PCIE is improved, which will improve the running speed of Xiangshan processor in FPGA difftest from 200K to 400~500K
> FPGA: send multiple packets within single xdma request

- .github/workflows/main.yml
- Makefile
- fpga.mk
- palladium.mk
- scripts/fpga_sim/ci.sh
- src/main/scala/DPIC.scala
- src/main/scala/Difftest.scala
- src/test/csrc/fpga/fpga_main.cpp
- src/test/csrc/fpga/xdma.cpp
- src/test/csrc/fpga/xdma.h
- src/test/csrc/fpga_sim/xdma_sim.cpp
- src/test/csrc/fpga_sim/xdma_sim.h
- src/test/csrc/vcs/vcs_main.cpp
- src/test/vsrc/fpga_sim/xdma_axi.v
- src/test/vsrc/fpga_sim/xdma_clock.v
- src/test/vsrc/fpga_sim/xdma_ctrl.v
- src/test/vsrc/fpga_sim/xdma_wrapper.v
- src/test/vsrc/vcs/top.v
- vcs.mk
- verilator.mk
This change supports software simulation of FPGA-host interacting with DUT in a xdma-like way. We use a simv process to simulate DUT and send difftest_data with xdma-like pcie. The simv process will interacting with fpga-host by share memory acting as xdma device.
Code of the xdma_ctrl.v is modified from the code of fengkehan <fengkehan@bosc.ac.cn> and fix some bugs.
> FPGA: support simulate fpga-host with dut

- Makefile
- src/test/csrc/common/common.h
- src/test/csrc/common/elfloader.h
- src/test/csrc/common/flash.cpp
- src/test/csrc/common/ram.cpp
- src/test/csrc/difftest/goldenmem.cpp
- src/test/csrc/verilator/emu.cpp
- src/test/csrc/verilator/emu.h
- src/test/csrc/verilator/gsim.cpp.inc
- src/test/csrc/verilator/gsim.h
- src/test/csrc/verilator/simulator.cpp
- src/test/csrc/verilator/simulator.h
- src/test/csrc/verilator/snapshot.cpp.inc
- src/test/csrc/verilator/snapshot.h
- src/test/csrc/verilator/verilator.cpp.inc
- src/test/csrc/verilator/verilator.h
- src/test/csrc/verilator/waveform.cpp.inc
This commit adds a standard abstraction for different RTL simulators for emu-mode, where the simulation is driven by C++ code at the top.
For various RTL simulators, they only need to implement the mandatory and some optional methods to work on DiffTest.
> emu: add an abstraction class for RTL simulators

- src/main/scala/common/WiringControl.scala
- src/main/scala/util/DataMirror.scala
`BoringUtils.tapAndRead` is introduced in chisel 6. Previous testing method ignored chisel 5.
> fix(wiring): teat chisel version in a more concrate way

- src/test/csrc/verilator/emu.cpp
- src/test/csrc/verilator/emu.h
Performance counters should be dumped even if NO_DIFF is specified. Note that these top interfaces always exist even if DiffTest is disabled.
> fix(emu): dump performance counters even if NO_DIFF

- Makefile
Simulators should support `-y` to use this feature. Input RTL_INCLUDE should be single or multiple space-separated directories.
> feat(Makefile): support including extra RTL files

- src/test/csrc/common/dut.h
- src/test/csrc/common/main.cpp
This would dump coverage metrics after every simulation when enabled.
> feat(dut): always show stats after simulation

- src/test/csrc/fpga/serial_port.cpp
This change disables the output buffer of the FPGA UART, enabling the host to print data from the serial port directly to the terminal in time.
> fix(serial): flush buffer at every print

- src/test/csrc/difftest/difftest.cpp
Some checks may be checked before first commits, such as NonRegInterruptPending may be valid at the end of reset, which will be used to sync Time interrupts to REF.
This change remove has_commit cond to allow check before.
> fix(difftest): enable check before first commit

- src/main/scala/Difftest.scala
This change add `define CPU_XX to generated DifftestMacros.v, then FPGA DiffTest can depends on the macro for switching logic between XS and NutShell.
> feat(difftest): add CPU to vMacros and fix typo

- src/main/scala/Preprocess.scala
vecdata should use DiffVecCommitData instead of DiffCommitData.
Using DiffCommitData causes multi-core compilation errors.
See:
https://github.com/OpenXiangShan/XiangShan/actions/runs/17786462508/job/50555731500#step:17:33
Sorry, I didn't check this PR(https://github.com/OpenXiangShan/difftest/pull/650) thoroughly.
Perhaps we should add additional multi-core CI tests for difftest?
> fix(Preprocess): `vecdata` should use `DiffVecCommitData`

- Makefile
This commit adds the support for RTL include with specified files or filelists. They will be detected in Makefile which appends the correct arguments to simulators.
> feat(make): allow RTL include with files and filelists

- src/main/scala/common/Mem.scala
- src/test/vsrc/common/ram.v
Some designs may read/write multiple blocks in one clock cycle, such as in a multi-channel DRAM system. To support this, this commit adds the multi-ported feature for DifftestMem.
Note this changes the naming for blackbox and may break GSIM support.
We also move the DPI-C functions to src/test/vsrc because they should not be declared multiple times, which may occur if multiple RWHelper's are called.
> feat(mem): support multi-ported memories

- src/main/scala/common/Mem.scala
After we add the support for multi-ported memory, we miss the i-loop.
> fix(mem): fix the missing i loop in mem.write
