OpenXiangShan/difftest

src/test/csrc/common/axi4.cpp, src/test/csrc/common/axi4.h, src/test/csrc/common/ram.cpp
Support 8-bytes AXI write strobes match
=> Support 8-bytes AXI write strobes match

src/test/csrc/difftest/difftest.cpp, src/test/csrc/difftest/spikedasm.cpp, src/test/csrc/difftest/spikedasm.h
* It will be automatically enabled if spike-dasm is in $PATH
=> display: spike-dasm commit instr trace

src/test/csrc/verilator/emu.cpp
This issue has been discussed in https://github.com/OpenXiangShan/difftest/issues/17
=> emu: fix incorrect waveform in DRAMSim3 cosim

src/test/csrc/verilator/emu.cpp
Example: --track-instr=0x80000000
=> addrtrack: accept addr of any base

src/test/csrc/common/lightsss.cpp, src/test/csrc/common/lightsss.h, src/test/csrc/verilator/emu.cpp, src/test/csrc/verilator/emu.h, verilator.mk
This commit moves LightSSS implementation to the common directory.
Support for verilator v4.210 and newer versions is added.
=> lightsss: moved to separate files

src/main/scala/Difftest.scala, src/test/csrc/difftest/difftest.cpp, src/test/csrc/difftest/difftest.h, src/test/csrc/difftest/interface.cpp, src/test/csrc/difftest/interface.h
* API is changed slightly to differentiate int regfile and fp regfile writeback
=> Fix dual-core difftest false positive assertions

src/main/scala/Difftest.scala, src/main/scala/DifftestMain.scala, src/test/csrc/difftest/difftest.cpp, src/test/csrc/difftest/difftest.h, src/test/csrc/difftest/interface.cpp, src/test/csrc/difftest/interface.h
-  separate dut.refill into i_refill and d_refill for difftest.
-  do both icache & dcache refill check.
-  add cache ID bit for identifying.
=>  add icache refill test

src/test/csrc/plugin/include/tllogger.h, src/test/csrc/plugin/tllogger/tllogger.cpp, src/test/csrc/verilator/emu.cpp, src/test/csrc/verilator/emu.h
* Usage: emu with --dump-tl --dump-tl-interval=CYCLES
=> tl-logger: support batch mode

src/main/scala/Difftest.scala, src/test/csrc/difftest/difftest.cpp, src/test/csrc/difftest/difftest.h, src/test/csrc/difftest/interface.cpp, src/test/csrc/difftest/interface.h
* when error, print robidx of each instruction
* print lqidx and sqidx of each ld/st instruction
=> misc: print robidx lsqidx in inst trace 

src/main/scala/Difftest.scala, src/test/csrc/difftest/difftest.cpp
1. adapt to modification : uopldx -> uopldxflags + uopldx.value
=> func(uopIdx): add end flag for uopIdx

config/config.h, config/verilator.mk, src/test/csrc/verilator/emu.cpp, src/test/csrc/verilator/emu.h, verilator.mk
Please add WITH_IPC option when compiling and use '-R' option when simulation
=> misc: Enable drawing ipc curve in verilator simulation

src/test/csrc/common/ram.cpp, src/test/csrc/common/ram.h, src/test/csrc/common/sparseram.cpp, src/test/csrc/common/sparseram.h, src/test/csrc/difftest/difftest.cpp, src/test/csrc/difftest/goldenmem.cpp, verilator.mk
=> Add raw elf file load.

src/main/scala/Difftest.scala, src/test/csrc/difftest/difftest.cpp
* add support for multiple commits in one commit event
=> difftest: support rob compression and instr fusion

.github/workflows/main.yml, src/test/csrc/common/coverage.cpp, src/test/csrc/common/coverage.h, src/test/csrc/common/dut.cpp, src/test/csrc/common/dut.h, src/test/csrc/common/main.cpp, src/test/csrc/difftest/difftest.cpp, src/test/csrc/difftest/difftest.h, src/test/csrc/verilator/emu.cpp, src/test/csrc/verilator/emu.h, verilator.mk
* support coverage metrics in RTL, via FIRRTL, or via LLVM
* integrated with XFUZZ framework
=> Add support for coverage-guided fuzzing

.github/workflows/main.yml, src/test/csrc/vcs/vcs_main.cpp, src/test/vsrc/vcs/top.v, vcs.mk
* add `VCS` macro to indicate VCS
* add a CI test case for using Verilator to simulate VCS top
=> Fix the VCS simulation flow and scripts

src/test/csrc/verilator/emu.cpp
It should follow the region specified with -b and -e.
=> emu: fix the range of dump-ref-trace

src/main/scala/Batch.scala, src/main/scala/DPIC.scala, src/main/scala/Difftest.scala
Macros for difftest functions, such as DPI-C and Batch, will be generated in the diffstate.h file.
=> Add C++ macros for difftest functions

src/main/scala/Bundles.scala, src/main/scala/DPIC.scala, src/main/scala/Difftest.scala, src/main/scala/Merge.scala
This should improve the code quality.
=> Move Bundle definitions to a separate file

src/test/csrc/common/ram.cpp, src/test/csrc/common/ram.h, src/test/csrc/common/sparseram.cpp, src/test/csrc/common/sparseram.h, src/test/csrc/difftest/goldenmem.cpp, src/test/csrc/vcs/vcs_main.cpp, src/test/csrc/verilator/emu.cpp, src/test/csrc/verilator/emu.h, vcs.mk, verilator.mk
Add sparse memory (support ELF load). Force RISC-V needs this feature.
=> Add sparse memory (support ELF load)

.github/workflows/main.yml, src/main/scala/Difftest.scala, src/main/scala/Squash.scala
* squash: N difftest bundles are squashed into 1 bundle
* batch: N difftest bundles are packed for transmission
=> Rename Merge to Squash

src/main/scala/DPIC.scala, src/main/scala/Gateway.scala
When enable batch-mode and set batch-size to 128, Number of lines of generated Nutshell verilog code will increase from 40k to 500k.
We pack fly-lines to reduce meaningless lines and speed up compilation. Now Nutshell has 80k lines of verilog code at batchsize 128 and 120k lines of code at batchsize 256. Most of increased lines is used for unpack signals and connect to the DPIC module.
=> Pack fly-line

src/main/scala/Gateway.scala
Default config doesn't require fly-lines. Disable it to speed up compilation
=> Disable Endpoint when DefaultConfig

src/main/scala/DPIC.scala, src/main/scala/Difftest.scala
Using fixed Class Declaration directly and remove redundant value. 
Enhance the correspondence between code and generated files.
=> Difftest,DPIC: Imporve Code readability

Makefile
This would accept SV projects by setting RTL_PREFIX=sv.
=>  makefile: add the RTL_SUFFIX macro

src/main/scala/DPIC.scala, src/main/scala/Difftest.scala, src/main/scala/Gateway.scala, src/main/scala/Squash.scala, src/main/scala/common/WiringControl.scala
A wrapper for chisel3.util.experimental.BoringUtils.addSource/addSink.
=> Add abstract wiring control support

src/main/scala/Difftest.scala, src/main/scala/common/WiringControl.scala
We provide several functions to create IOs or wires via DifftestWiring.
* remove extra IO support in Difftest.finish
* separate createPendingWires and createExtraIOs
=> wiring: disabled by default

src/main/scala/common/Flash.scala, src/test/vsrc/vcs/top.v
* Modify some variable nameing
* Move reg declaration outside initial block
=> Fix some non-logical bugs for Palladium

src/main/scala/common/Flash.scala, src/main/scala/common/Mem.scala
Flash: use default instr when no flash path specified. 
We also use byteread from file to avoid problem about byte-order.
=> Flash, Mem: support specified path when running with SYNTHESIS

src/main/scala/Bundles.scala, src/main/scala/Difftest.scala, src/main/scala/Gateway.scala, src/main/scala/Squash.scala
The valid bits are actually defined in the base bundle. Thus, we move them from DifftestBundle to DifftestBaseBundle.
=> Support needUpdate and defaultUpdate for DifftestBaseBundle

src/main/scala/Difftest.scala, src/main/scala/Gateway.scala
We wrap the gateway return values in a case class for better code readability and code structure.
The results of the gateway consist of:
* C++ macros
* Verilog macros
* Extra difftest bundles
* DiffTest step
=> Gateway: wrap results in a case class

.github/workflows/format.yml, .github/workflows/main.yml, .scalafmt.conf, Makefile, src/main/scala/Bundles.scala, src/main/scala/DPIC.scala, src/main/scala/Difftest.scala, src/main/scala/Gateway.scala, src/main/scala/Squash.scala, src/main/scala/common/Flash.scala, src/main/scala/common/Mem.scala, src/main/scala/common/SDCard.scala, src/main/scala/common/WiringControl.scala, src/test/scala/DifftestMain.scala
It will automatically format the code on pushes/PRs to master using scalafmt.
=> Add the Scala formatter with GitHub Actions

.github/workflows/main.yml
Indentation style of GatewayConfig param is changed by scalaFmt. We modify sed to adapting that.
=> CI: modify sed for scalaFmt

.github/workflows/main.yml
* use rocket-chip to test the fuzzer (should have no bugs)
=> CI: update the fuzzing tests

src/test/csrc/vcs/vcs_main.cpp
When running with --workload-lilst, simv_init is reinitialized multiple times in a single startup, and the pointer from the last simv_init request needs to be destroyed before doing so. This commit fixed an issue with incomplete memory deallocation when exiting the program, and release the list file correctly when using the workload list
=> vcs: fix resources deallocation of simulation

vcs.mk
=> add ROT to vcs.mk

src/main/scala/common/Flash.scala
=> flash: add the read method

src/main/scala/common/Mem.scala
MemRWHelper imports the same DPI-C functions as MemRHelper and MemWHelper. When they are instantiated at the same time, specifically when both single-port and dual-port DifftestMem are created, they will bring duplicated DPI-C function imports in different design files. The conflict DPI-C names will abort the RTL simulator.
We remove the MemRWHelper and replace them with MemRHelper and MemWHelper.
=> Remove MemRHelper/MemWHelper to avoid DPI-C conflicts

src/test/csrc/common/coverage.h, src/test/csrc/common/dut.h, src/test/csrc/common/ram.h
Clang format seems to be updated last night and finds some missing format issues.
=> Apply Clang format

.github/workflows/format.yml, Makefile, verilator.mk
Add Version Check and Install note into Makefile. So user should ensure correct clang-format version for difftest.
=> Makefile: check clang-format version

src/main/scala/Squash.scala
First commit of multicore is not valid in same cycle, previous single control logic only works for single core.
This change mark init state for each core, first commits of every core will be force-sync.
=> squash: fix force-sync of first-commit for multicore

verilator.mk
This commit adds an OPT_FAST option for choosing the optimization level for verilator-generated C sources, which is useful to address the slow compile time issue on clang-18. And also addressed #395.
The changes to address #395 are:
1. Remove the dependence of `$(EMU_MK)` on build_emu_local
A required chain exists in the current ventilator.mk:
`build_emu_local` -> `$(EMU_MK)` -> `$(EMU_DEPS)` -> `$(EMU_CXXFILES)` -> `$(SIM_CXXFILES)`
However, when we have `WITH_CHISELDB=1` which is default, we will do `SIM_CXXFILES += $(BUILD_DIR)/chisel_db.cpp` then, `chisel_db.cpp` will be required by build_emu_local. If this file does not exist, the make command will fail. However, we pass `WITH_CHISELDB` from another Makefile, if this does not pass to ssh, building on another host will fail. If some …
=> verilator.mk: Add OPT_FAST option and refractor build flow

verilator.mk
When building PGO Verilator EMU on a remote server with shared NFS mounted with async. After compiling on a remote server, the dirty medication on filesystem may not been flushed to the NFS server, or (and) the localhost has not received a cache coherence snoop request from the NFS server. In this case, executing emu on localhost may fail because the file cannot be found. This commit addressed this by adding sync to the build_dir and emu_dir. So we have the right directory metadata synced between the build server and localhost. I tried to build a PGO verilator emu several times on a remote server. It no longer fails.
=> verilator.mk: Sync BUILD_DIR and EMU_DIR for PGO

src/main/scala/util/VerificationExtractor.scala
We add an index argument for the VerificationExtractorSink annotation to support specifying a specific assertion bit for wiring.
Example usage:
```scala
class AssertionTracker extends Module {
val io = IO(new Bundle {
val valid = Output(Bool())
})
val assertions = Seq.fill(256)(RegInit(false.B))
VerificationExtractor.sink(assertions)
io.valid := VecInit(assertions).asUInt.orR
}
```
=> util: support wiring any assertion bit via index

src/main/scala/util/VerificationExtractor.scala
This commit changes single assertion bits to a concatenated UInt and uses this UInt for wiring. This change effectively reduces the number of wirings for large designs, probably improving the wiring performance.
=> verification: concat assertion bits for wiring

src/main/scala/Bundles.scala, src/main/scala/Difftest.scala, src/test/csrc/difftest/refproxy.cpp, src/test/csrc/difftest/refproxy.h, src/test/scala/DifftestMain.scala
*add triggerCSRState in difftest
=> difftest: support trigger csr

src/main/scala/Difftest.scala
In some cases, it may be necessary to write some files in append mode, and this requirement will be used in another pr
=> difftest: Add an optional way to append to streamToFile

src/main/scala/DPIC.scala, src/main/scala/Difftest.scala
In Batch DPIC function, some signals, such as coreid/index/address, will serves as buffer locating info, instead of actually transmitted. So we cluster transmitted data to simplify Parsing logic.
Such problem is introdeced by new Hardware elements instanced by DifftestBundle Trait, which results in Locate info mixed into transmitted data.
To make byteAlign funtions compatible for both Hardware and Chisel type, we use DataMirror to check bindings.
=> Batch: reorder bundle elements to cluster transmitted Data 

src/test/csrc/difftest/difftest.cpp, src/test/csrc/difftest/refproxy.h
=> fix(csr): fix struct non-reg interrupt pending to order

src/main/scala/Difftest.scala, src/test/scala/DifftestTop.scala
Fill in the missing characters when generating svh files
=> difftest: fix instances of generated Svh Interface

Makefile, src/test/csrc/common/elfloader.cpp, src/test/csrc/common/elfloader.h, src/test/csrc/common/ram.cpp
This adds the Elf format as an additional pre-loadable file format. Similar to the compressed ones.
=> feat(ram): Add flat Elf loading capabilities

src/main/scala/Difftest.scala
=> Fix the code style of streamToFile def

src/main/scala/DPIC.scala, src/main/scala/Difftest.scala, src/main/scala/Trace.scala, src/main/scala/common/FileControl.scala
This allows users to create files at the generated-src directory by default.
=> difftest: add a separate FileControl class

src/main/scala/Difftest.scala
* use function arguments instead of global variables
=> fix(difftest): remove unused mutable lists

src/main/scala/Difftest.scala, src/main/scala/util/Profile.scala
This allows the user to get all current interfaces.
=> Difftest: add the get_all_interfaces API

scripts/st_tools/interface.py
Provides a script to modify the gatewayendpoint to the interface connection way, for the difftest connection process of the ST environment, and supports the removal of simv top and the removal of simv top from filelist
=> difftest: Provides a script to change the gatewayendpoint to interface

src/main/scala/DPIC.scala, src/main/scala/Difftest.scala
We support pattern matching of Bundle for elements of DifftestBundle. This allows the usage of Bundle when defining a DifftestBundle.
Also, the previous DPI-C implementation ignores bundles and assumes all top-level signals are either Vec or UInt. This commit fixes it by reusing the recursive function defined in DifftestBundle to get all elements in UInt. This ensures the same functionality between DPI-C and DifftestBundle.
=> feat(difftest): support parsing recursive bundles

scripts/st_tools/interface.py
Remove unused functions and optimize the format of the generated files
=> scripts: fix format of generated interface between DUT and DiffTest

src/test/csrc/vcs/vcs_main.cpp, src/test/vsrc/vcs/DifftestEndpoint.sv
Since the syntax on some emulators does not support calling the task function in DPIC, the implementation of emptying the performance counter is modified to judge according to the return value of simv
=> vcs: warmup is implemented using the return value of simv_nstp

src/main/scala/Batch.scala
Previous we collect data from different group by MuxTree and Cat, however it leads to bad timing for multi-level mux, and consuming more gates if we insert some register to optimize timing.
This change use three stage batch for better area and timing: 
Stage 1: we use BatchCluster to cluster data with same class in same cycle, which means make valid data close to each other. As each bundle has same width, we can simplify use mux to choose location. Note we also insert a RegNext before cluster to cut off combinatorial logic circuit.
Stage 2: we use BatchCollector to collect data with different class, but also in same cycle. As each group_data has different width and different valid bytes, we use shift to collect group_data instead of original muxtree for better area and timing.
Stage 3: we …
=> Batch: adopt cluster and shifter for better area and timing

.github/workflows/main.yml, .github/workflows/nightly.yml
xs-env provides general containers for running tests.
=> feat(ci): use OpenXiangShan docker to run tests

src/main/scala/common/Mem.scala
GSIM only support async read of DiffTestMEM to ensure combinational logic inside extmodule, while Palladium only support sync read to only trigger DPI-C in clock posedge.
This change support both async and sync read, which can be switched by port a_sync with value 1/0 when defining GSIM or not.
=> fix(mem): support both async and sync read

src/generator/chisel/DifftestMain.scala, src/generator/chisel3/DifftestMain.scala, src/main/scala/Coverage.scala, src/main/scala/Difftest.scala, src/test/scala/DifftestTop.scala
We will add some customized FIRTOOL options for DiffTest. Thus, we change the function to return a list of FirtoolOption's. This may bring compatibility issues.
Specifically, we have added the coverage options.
=> feat(cover): add customized firtool options

src/main/scala/Batch.scala
BatchCluster collected same-type bundles with O(n^2) complexity, resulting a significant area when grouping a lot of same-type bundles. For example, there is 48 StoreEvents in Default Diff, and 64 regfile elems with Delta enabled.
This patch reduces complexity by grouping multi-bundle into groups of 8, such as 6x8 cluster for StoreEvent. And Batch also directly concat single-bundle instead of using extra shifter.
Overall, this change reduces 1/3 area for BatchCluster when BasicDiff.
=> Batch: group multi-bundle to 8 and cat single-bundle

scripts/coverage/coverage.py, scripts/coverage/statistics.py
* also fix the typo "coverred"
=> fix(cover): support modules with parameters

src/test/csrc/plugin/simfrontend/ftq.cpp, src/test/csrc/plugin/simfrontend/ftq.h, src/test/csrc/plugin/simfrontend/simfrontend.cpp, src/test/csrc/plugin/simfrontend/simfrontend.h
**This PR only affects simfrontend and does not impact other modules in difftest.**
Fixed issues where incorrect handling of branch instructions caused failures during redirection.
Primarily addresses the FTQ requirements for jump/branch instructions in real RTL.
=> fix(simfrontend): fix execution flow errors caused by redirect
